config/routes.rb
Helpdesk::Engine.routes.draw do
  default_url_options :host => "suporte.neemo.com.br"
# Rails.application.routes.draw do
  scope "(:locale)", :locale => /pl|pt|en/ do
    
    
    # Admin only roots
    namespace :admin do
      resources :tickets do
        get :assign, on: :member
      end
      resources :ticket_types
      resources :faqs do
        post :sort, on: :collection
      end
      resources :subscribers
      root :to => "tickets#index"
    end

    resources :faqs, :only => [ :index ]
    resources :tickets, :except => [ :edit, :destroy]
    root :to => "tickets#index"

    
  end
end

app/models/helpdesk/comment.rb
module Helpdesk
  class Comment < ActiveRecord::Base
    belongs_to :author, :class_name => Helpdesk.user_class.to_s
    belongs_to :ticket

    default_scope -> {includes(:author).order('id ASC')}
    scope :pub,  -> { where(public: true)}

    after_create :send_email
    after_create :check_reopen

    def check_reopen
      if ticket.requester == author
        ticket.update_column(:status ,:waiting)
      end
    end


    def send_email
      if self.public?
        if ticket.requester == author
          Helpdesk::NotificationsMailer.comment_by_requester_notification(self).deliver if ticket.requester
          Helpdesk::NotificationsMailer.comment_by_requester_confirmation(self).deliver if Helpdesk.send_confirmation_emails
        else
          Helpdesk::NotificationsMailer.comment_by_helpdesk_notification(self).deliver if ticket.requester
          Helpdesk::NotificationsMailer.comment_by_helpdesk_confirmation(self).deliver if Helpdesk.send_confirmation_emails
        end
      end
    end
  end
end

app/models/helpdesk/faq.rb
module Helpdesk
  class Faq < ActiveRecord::Base
    translates :title, :text
    accepts_nested_attributes_for :translations

    default_scope order('position ASC').includes(:translations)

    scope :active,  -> {where(active:  true)}
    scope :inactive,  -> {where(active: false)}
  end
end

app/models/helpdesk/subscriber.rb
module Helpdesk
  class Subscriber < ActiveRecord::Base
    scope :confirmed,  where('confirmed = ? ',true)
    scope :unconfirmed,  where('confirmed = ? ',false)

    validates_presence_of :email

  end
end

app/models/helpdesk/ticket_type.rb
module Helpdesk
  class TicketType < ActiveRecord::Base
    translates :title
    accepts_nested_attributes_for :translations

    default_scope ->{order('position ASC')}

    scope :active,  -> {where(active:  true)}
    scope :inactive,  -> {where(active: false)}

  end
end

app/controllers/helpdesk/admin/base_controller.rb
module Helpdesk
  module Admin
    class BaseController < Helpdesk::ApplicationController

      helper Helpdesk::Engine.helpers
      # helper Helpdesk::ApplicationHelper
      before_filter :authenticate_helpdesk_admin
      before_filter :my_tickets

      layout 'helpdesk/admin'

      private
        #methods helpdesk_user & helpdesk_admin? - must by defined in file app/application_controller

        def authenticate_helpdesk_admin
          unless helpdesk_admin?
            redirect_to main_app.root_url, notice:'You have no power here!'
          end
        end

        def my_tickets
          @my_tickets = Ticket
          .includes(:comments=>[:author])
          .includes(:requester)
          .includes(:assignee)
          .includes(:ticket_type)
          .where('assignee_id = ?', helpdesk_user.id)
          .active
        end
    end
  end
end

app/controllers/helpdesk/admin/dashboard_controller.rb
class Helpdesk::Admin::DashboardController < Helpdesk::Admin::BaseController

      def index
        #@tickets = Ticket.all
      end
end

app/controllers/helpdesk/admin/faqs_controller.rb
class Helpdesk::Admin::FaqsController < Helpdesk::Admin::BaseController

  def sort
    params[:faqs].each_with_index do |id, index|
      Helpdesk::Faq.update_all(['position=?', index+1], ['id=?', id])
    end
    render :nothing => true
  end
  # GET /faqs
  # GET /faqs.json
  def index
    if params[:faqs] == 'active'
      @faqs = Helpdesk::Faq.active
    elsif params[:faqs] == 'inactive'
      @faqs = Helpdesk::Faq.inactive
    else
      @faqs = Helpdesk::Faq.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faqs }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @faq = Helpdesk::Faq.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/new
  # GET /faqs/new.json
  def new
    @faq = Helpdesk::Faq.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/1/edit
  def edit
    @faq = Helpdesk::Faq.find(params[:id])
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Helpdesk::Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to admin_faqs_url, notice: 'Faq was successfully created.' }
        format.json { render json: @faq, status: :created, location: @faq }
      else
        format.html { render action: "new" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /faqs/1
  # PUT /faqs/1.json
  def update
    @faq = Helpdesk::Faq.find(params[:id])

    respond_to do |format|
      if @faq.update_attributes(faq_params)
        format.html { redirect_to admin_faqs_url, notice: 'Faq was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq = Helpdesk::Faq.find(params[:id])
    @faq.destroy

    respond_to do |format|
      format.html { redirect_to admin_faqs_url }
      format.json { head :no_content }
    end
  end

  private
  def faq_params
    params.require(:faq).permit(:active, :position, :title, :text, translations_attributes:[:id,:locale,:title,:text])
  end
end

app/controllers/helpdesk/admin/subscribers_controller.rb
class Helpdesk::Admin::SubscribersController < Helpdesk::Admin::BaseController

  def index
    @subscribers = Helpdesk::Subscriber.page(params[:page])
  end

  def new
    @subscriber = Helpdesk::Subscriber.new()
  end

  def create
    @subscriber = Helpdesk::Subscriber.new(subscriber_params)
    if @subscriber.save
      redirect_to admin_subscribers_path, notice: t('subscribers.created')
    else
      render action: "index"
    end
  end

  def edit
    @subscriber = Helpdesk::Subscriber.find(params[:id])
  end

  # PUT /subscribers/1
  # PUT /subscribers/1.json
  def update
    @subscriber = Helpdesk::Subscriber.find(params[:id])

    if @subscriber.update_attributes(subscriber_params)
      redirect_to admin_subscribers_path, notice: 'Subscriber was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber = Helpdesk::Subscriber.find_by_hashcode(params[:hashcode])
    @subscriber.destroy
    redirect_to root_path
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:confirmed, :email, :hashcode, :lang, :name)
  end
end

app/controllers/helpdesk/admin/ticket_types_controller.rb
class Helpdesk::Admin::TicketTypesController < Helpdesk::Admin::BaseController

  def index
    @ticket_types = Helpdesk::TicketType.all
  end

  def show
    @ticket_type = Helpdesk::TicketType.find(params[:id])
  end

  def new
    @ticket_type = Helpdesk::TicketType.new
  end

  def edit
    @ticket_type = Helpdesk::TicketType.find(params[:id])
  end

  def create
    @ticket_type = Helpdesk::TicketType.new(ticket_type_params)
    if @ticket_type.save
      redirect_to admin_ticket_types_url, notice: 'Ticket type was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @ticket_type = Helpdesk::TicketType.find(params[:id])
    if @ticket_type.update_attributes(ticket_type_params)
      redirect_to admin_ticket_types_url, notice: 'Ticket type was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @ticket_type = Helpdesk::TicketType.find(params[:id])
    @ticket_type.destroy

    respond_to do |format|
      format.html { redirect_to admin_ticket_types_url }
      format.json { head :no_content }
    end
  end

  private

  def ticket_type_params
    params.require(:ticket_type).permit(:id, :active,:position,:title,:tr_class,translations_attributes:[:title, :id, :locale])
  end
end

app/controllers/helpdesk/admin/tickets_controller.rb
class Helpdesk::Admin::TicketsController < Helpdesk::Admin::BaseController

  def index
    if params[:tickets] == 'unassigned'
      @tickets = Helpdesk::Ticket.unassigned.scoped
    elsif params[:tickets] == 'closed'
      @tickets = Helpdesk::Ticket.closed.scoped
    elsif params[:tickets] == 'active'
      @tickets = Helpdesk::Ticket.active.scoped
    elsif params[:tickets] == 'all'
      @tickets = Helpdesk::Ticket.scoped
    else
      @tickets = my_tickets.active
    end
    @tickets = @tickets.includes(:requester)
                        .includes(:assignee)
                        .includes(:ticket_type)
                        .page(params[:page])

    render 'list'
  end

  def assign
    @ticket = Helpdesk::Ticket.find(params[:id])
    if @ticket.update_column(:assignee_id, helpdesk_user)
      redirect_to admin_ticket_path,
        notice: t('helpdesk.tickets.is_now_assigned',subject: @ticket.subject)
    else
      redirect_to admin_ticket_path
    end
  end

  def new
    @ticket = Helpdesk::Ticket.new
    @ticket.status = Helpdesk::Ticket::STATUSES[0][0]
  end

  def edit
    @ticket = Helpdesk::Ticket.find(params[:id])

  end

  def show
    @ticket = Helpdesk::Ticket.find(params[:id])

  end

  def create
    @ticket = Helpdesk::Ticket.new(ticket_params)
    if @ticket.save
      redirect_to admin_ticket_path(@ticket)
    else
      render action: "new"
    end
  end

  def update
    @ticket = Helpdesk::Ticket.find(params[:id])
    if @ticket.update_attributes(ticket_params)
      unless @ticket.assignee
        @ticket.update_column(:assignee_id, helpdesk_user)
      end
      redirect_to admin_ticket_path
    else
      render action: "new"
    end
  end


   private

    def ticket_params
      params.require(:ticket).permit(:status,:requester_id,:assignee_id,:ticket_type_id, :subject, :description,comments_attributes:[:author_id, :comment, :public])
    end

end

app/controllers/helpdesk/application_controller.rb
module Helpdesk
  class ApplicationController < ::ApplicationController
    before_filter :ensure_user, :if => Proc.new { Helpdesk.require_user }

    helper Helpdesk::Engine.helpers

    layout 'helpdesk/user'

    def ensure_user
      unless helpdesk_user
        redirect_to main_app.send(Helpdesk.sign_in_url)
      end
    end

    def default_url_options(options={})
      { :locale => I18n.locale}
    end

  end
end

app/controllers/helpdesk/dashboard_controller.rb
module Helpdesk
  class DashboardController < Helpdesk::ApplicationController


    before_filter :my_tickets

    def index
    end


    def show
    end


    def my_tickets
      @my_tickets = Helpdesk::Ticket
      .includes(:comments=>[:author])
      .includes(:requester)
      .includes(:assignee)
      .includes(:ticket_type)
      .where('requester_id = ?', helpdesk_user.id)
    end


  end
end

app/controllers/helpdesk/faqs_controller.rb
module Helpdesk
  class FaqsController < Helpdesk::ApplicationController
    def index
      @faqs = Helpdesk::Faq.active
    end
  end
end

app/controllers/helpdesk/subscribers_controller.rb
module Helpdesk
  class SubscribersController < Helpdesk::ApplicationController


    def new
      @subscriber = Subscriber.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @subscriber }
      end
    end

    def create
      @subscriber = Subscriber.new(subscriber_params)

      respond_to do |format|
        if @subscriber.save
          format.html { redirect_to @subscriber, notice: 'Subscriber was successfully created.' }
          format.json { render json: @subscriber, status: :created, location: @subscriber }
        else
          format.html { render action: "new" }
          format.json { render json: @subscriber.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /subscribers/1
    # PUT /subscribers/1.json
    def update
      @subscriber = Subscriber.find(params[:id])

      respond_to do |format|
        if @subscriber.update_attributes(subscriber_params)
          format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @subscriber.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /subscribers/1
    # DELETE /subscribers/1.json
    def destroy
      @subscriber = Subscriber.find(params[:id])
      @subscriber.destroy

      respond_to do |format|
        format.html { redirect_to subscribers_url }
        format.json { head :no_content }
      end
    end

    private

    def subscriber_params
      params.require(:subscriber).permit(:email,:lang, :name)
    end
  end
end

app/controllers/helpdesk/tickets_controller.rb
module Helpdesk
  class TicketsController < Helpdesk::ApplicationController

    helper TicketsHelper

    # GET /tickets
    # GET /tickets.json
    def index
      if params[:tickets] == 'closed'
        @tickets = Helpdesk::Ticket.where(:requester_id => helpdesk_user.id).closed.page(params[:page])
      else
        @tickets = Helpdesk::Ticket.where(:requester_id => helpdesk_user.id).active.page(params[:page])
      end


      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @tickets }
      end
    end

    # GET /tickets/1
    # GET /tickets/1.json
    def show
      @tickets_count = Helpdesk::Ticket.where(:requester_id => helpdesk_user.id).active.count
      @ticket = Helpdesk::Ticket.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @ticket }
      end
    end

    # GET /tickets/new
    # GET /tickets/new.json
    def new
      @tickets_count = Helpdesk::Ticket.where(:requester_id => helpdesk_user.id).active.count
      @ticket = Helpdesk::Ticket.new
      @ticket.status = Helpdesk::Ticket::STATUSES[0][0]

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @ticket }
      end
    end

    def create
      @ticket = Helpdesk::Ticket.new(ticket_params)
      @ticket.requester = helpdesk_user
      @ticket.status = Helpdesk::Ticket::STATUSES[0][0]

      respond_to do |format|
        if @ticket.save
          format.html { redirect_to tickets_url, notice: 'Ticket was successfully created.' }
          format.json { render json: @ticket, status: :created, location: @ticket }
        else
          format.html { render action: "new" }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /tickets/1
    # PUT /tickets/1.json
    def update
      @ticket = Helpdesk::Ticket.find(params[:id])

      respond_to do |format|
        if @ticket.update_attributes(ticket_params)
          format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.'}
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end
    end


    private

    def ticket_params
      params.require(:ticket).permit( :ticket_type_id, :subject, :description,comments_attributes:[:author_id, :comment, :public])
    end

  end
end

app/helpers/helpdesk/admin/dashboard_helper.rb
module Helpdesk
  module Admin
    module DashboardHelper
    end
  end
end

app/helpers/helpdesk/admin/tickets_helper.rb
module Helpdesk
  module Admin::TicketsHelper
    def humanize_with_i18n(string, scope = [])
      I18n.t string, scope: scope, default: string.humanize
    end

    # The method prefix tells me that this should be in an object
    # But it doesn't belong in our model, does it?
    def tickets_statuses_for_select
      Helpdesk::Ticket::STATUSES.map { |s| [humanize_with_i18n(s[0].to_s,'helpdesk.tickets.statuses'),s[0]] }
    end
  end
end

app/helpers/helpdesk/dashboard_helper.rb
module Helpdesk
  module DashboardHelper
  end
end

app/helpers/helpdesk/faqs_helper.rb
module Helpdesk
  module FaqsHelper
  end
end

app/views/layouts/helpdesk/_topmenu.html.haml
%nav.navbar.navbar-default#site_topmmenu{role: 'navigation'}
  .navbar-header
    %button.navbar-toggle{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    =link_to Helpdesk.site_address, main_app.root_path, :class=>'navbar-brand', :title => t('helpdesk.name')
    =link_to t('helpdesk.name'), admin_root_path, :class=>'navbar-brand', :title => t('helpdesk.name')
  #bs-navbar-collapse-1.collapse.navbar-collapse.in
    %ul.nav.navbar-nav
      = menu_li t('helpdesk.tickets.title'),admin_tickets_path
      = menu_li t('helpdesk.ticket_types.title'),admin_ticket_types_path
      = menu_li t('helpdesk.subscribers.title'),admin_subscribers_path
      = menu_li t('helpdesk.faqs.title'),admin_faqs_path

    %ul.nav.navbar-nav.navbar-right
      %li.dropdown.user
        = link_to current_user.send(Helpdesk.display_user.to_sym), "#",:class=>"dropdown-toggle",data:{toggle:"dropdown"}
        %ul.dropdown-menu
          %li=link_to 'Home',main_app.root_path
          %li=link_to t('users.sign_out'),main_app.destroy_user_session_path, :method => :delete, :class => 'icon exit blue'

      %li.dropdown
        = link_to t('helpdesk.lang'),"#",:class=>"dropdown-toggle",data:{toggle:"dropdown"}
        %ul.dropdown-menu
          %li= link_to "Português", params.merge({:locale => "pt"})
          %li= link_to "English", params.merge({:locale => :en})
          

app/views/layouts/helpdesk/_topuser.html.haml
%nav.navbar.navbar-default#site_topmmenu{role: 'navigation'}
  .navbar-header
    %button.navbar-toggle{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    =link_to Helpdesk.site_address, main_app.root_path, :class=>'navbar-brand', :title => Helpdesk.site_address
    =link_to Helpdesk.name, root_path, :class=>'navbar-brand', :title => Helpdesk.name
  #bs-navbar-collapse-1.collapse.navbar-collapse.in
    %ul.nav.navbar-nav
      = menu_li t('helpdesk.tickets.title'),tickets_path
      = menu_li t('helpdesk.faq'),faqs_path

    %ul.nav.navbar-nav.navbar-right
      %li.dropdown.user
        = link_to current_user.send(Helpdesk.display_user.to_sym), "#",:class=>"dropdown-toggle",data:{toggle:"dropdown"}
        %ul.dropdown-menu
          %li=link_to 'Home',main_app.root_path
          %li=link_to t('users.sign_out'),main_app.destroy_user_session_path, :method => :delete, :class => 'icon exit blue'

      %li.dropdown
        = link_to t('helpdesk.lang'),"#",:class=>"dropdown-toggle",data:{toggle:"dropdown"}
        %ul.dropdown-menu
          %li= link_to "Português", params.merge({:locale => "pt"})
          %li= link_to "English", params.merge({:locale => :en})
          

app/views/layouts/helpdesk/admin.html.haml
!!!
%html
  %head
    %title
      = t :name, :scope => :helpdesk
    = javascript_include_tag "helpdesk/application"
    = stylesheet_link_tag    "helpdesk/admin", :media => "all"
    = javascript_tag "$(document).ready(function(){ $('.dropdown-toggle').dropdown();$('.alert').alert();})"
    = csrf_meta_tags
    = yield :head
  %body
    .container
      = render 'layouts/helpdesk/topmenu'
      .content
        .row
          .col.col-md-3#site_leftmenu
            =yield :left
          .col.col-md-9#site_leftmenu
            .flash
            - flash.each do |type, message|
              %div{:class => "alert alert-#{type}", "data-alert"=>"alert"}
                =link_to "x",'#', :class=>'close', :'data-dismiss'=>"alert"
                %p= message
            - if content_for?(:title)
              .panel.panel-default
                .panel-heading
                  %h3.panel-title
                    = content_for?(:title) ? content_for(:title) : ''
                .panel-body
                  = yield
            - else
              = yield
  =yield :scripts

app/views/layouts/helpdesk/user.html.haml
!!!
%html
  %head
    %title
      = t :name, :scope => :helpdesk
    = javascript_include_tag "helpdesk/application"
    = stylesheet_link_tag    "helpdesk/application", :media => "all"
    = javascript_tag "$(document).ready(function(){ $('.dropdown-toggle').dropdown();$('.alert').alert();})"
    = csrf_meta_tags
    = yield :head
  %body
    .container
      = render 'layouts/helpdesk/topuser'
      .content
        .row
          .col.col-md-3#site_leftmenu
            =yield :left
          .col.col-md-9#site_leftmenu
            .flash
            - flash.each do |type, message|
              %div{:class => "alert alert-#{type}", "data-alert"=>"alert"}
                =link_to "x",'#', :class=>'close', :'data-dismiss'=>"alert"
                %p= message
            - if content_for?(:title)
              .panel.panel-default
                .panel-heading
                  %h3.panel-title
                    = content_for?(:title) ? content_for(:title) : ''
                .panel-body
                  = yield
            - else
              = yield
  =yield :scripts