config/routes.rb
Helpdesk::Engine.routes.draw do
  default_url_options :host => "suporte.neemo.com.br"
# Rails.application.routes.draw do
  scope "(:locale)", :locale => /pl|pt|en/ do
    
    
    # Admin only roots
    namespace :admin do
      resources :tickets do
        get :assign, on: :member
      end
      resources :ticket_types
      resources :faqs do
        post :sort, on: :collection
      end
      resources :subscribers
      root :to => "tickets#index"
    end

    resources :faqs, :only => [ :index ]
    resources :tickets, :except => [ :edit, :destroy]
    root :to => "tickets#index"

    
  end
end

app/controllers/helpdesk/admin/ticket_types_controller.rb
class Helpdesk::Admin::TicketTypesController < Helpdesk::Admin::BaseController

  def index
    @ticket_types = Helpdesk::TicketType.all
  end

  def show
    @ticket_type = Helpdesk::TicketType.find(params[:id])
  end

  def new
    @ticket_type = Helpdesk::TicketType.new
  end

  def edit
    @ticket_type = Helpdesk::TicketType.find(params[:id])
  end

  def create
    @ticket_type = Helpdesk::TicketType.new(ticket_type_params)
    if @ticket_type.save
      redirect_to admin_ticket_types_url, notice: 'Ticket type was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @ticket_type = Helpdesk::TicketType.find(params[:id])
    if @ticket_type.update_attributes(ticket_type_params)
      redirect_to admin_ticket_types_url, notice: 'Ticket type was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @ticket_type = Helpdesk::TicketType.find(params[:id])
    @ticket_type.destroy

    respond_to do |format|
      format.html { redirect_to admin_ticket_types_url }
      format.json { head :no_content }
    end
  end

  private

  def ticket_type_params
    params.require(:ticket_type).permit(:id, :active,:position,:title,:tr_class,translations_attributes:[:title, :id, :locale])
  end
end

app/views/helpdesk/admin/ticket_types/_form.html.haml
= simple_form_for [:admin, @ticket_type] do |f|
  - if @ticket_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ticket_type.errors.count, "error")} prohibited this ticket_type from being saved:"
      %ul
        - @ticket_type.errors.full_messages.each do |msg|
          %li= msg



  - I18n.available_locales.each do |locale|
    %h1
      = locale
      = f.globalize_fields_for locale do |g|
        = g.input :title

  
  = f.input :tr_class
  = f.input :active
  = f.submit 'Save',:class=>'btn btn-promary'

app/views/helpdesk/admin/ticket_types/_menu.html.haml
- content_for :left do
  = menu_left t('helpdesk.ticket_types.title') do
    = menu_li ico('pencil') + t('helpdesk.ticket_types.new'), new_admin_ticket_type_url
    %li.divider
    = menu_li ico('eye-open') + "#{t('helpdesk.ticket_types.active')} ", admin_ticket_types_url(:ticket_types => 'active')
    = menu_li ico('folder-open') + "#{t('helpdesk.tickets.unassigned')} ", admin_ticket_types_url(:ticket_types => 'inactive')
    %li.divider
    = menu_li ico('list') + t('helpdesk.ticket_types.all'), admin_ticket_types_url(:ticket_types => 'all')

/ (#{Helpdesk::TicketType.active.count})
/ (#{Helpdesk::TicketType.inactive.count})

app/views/helpdesk/admin/ticket_types/edit.html.haml
= render 'menu'

- content_for :title do
  Editing ticket_type

= render 'form'

= link_to 'Show', admin_ticket_type_path(@ticket_type)
\|
= link_to 'Back', admin_ticket_types_path

app/views/helpdesk/admin/ticket_types/index.html.haml
= render 'menu'

- content_for :title do
  -if params[:ticket_types] && params[:ticket_types] == 'active'
    = t('helpdesk.ticket_types.active')
  -elsif params[:ticket_types] && params[:ticket_types] == 'inactive'
    = t('helpdesk.ticket_types.inactive')
  -else
    = t('helpdesk.ticket_types.all')


%table.table.table-hover
  %tr
    %th Title
    %th
    %th
    %th

  - @ticket_types.each do |ticket_type|
    %tr{:class=>ticket_type.tr_class}
      %td= ticket_type.title
      %td= link_to 'Show', admin_ticket_type_path(ticket_type)
      %td= link_to 'Edit', edit_admin_ticket_type_path(ticket_type)
      %td= link_to 'Destroy', admin_ticket_type_path(ticket_type), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sugestion type', new_admin_ticket_type_path

app/views/helpdesk/admin/ticket_types/new.html.haml
= render 'menu'

- content_for :title do
  New ticket_type

= render 'form'

= link_to 'Back', admin_ticket_types_path

app/views/helpdesk/admin/ticket_types/show.html.haml
= render 'menu'

%p#notice= notice

%p
  = @ticket_type.title
  

= link_to 'Edit', edit_admin_ticket_type_path(@ticket_type)
\|
= link_to 'Back', admin_ticket_types_path