config/routes.rb
Helpdesk::Engine.routes.draw do
  default_url_options :host => "suporte.neemo.com.br"
# Rails.application.routes.draw do
  scope "(:locale)", :locale => /pl|pt|en/ do
    
    
    # Admin only roots
    namespace :admin do
      resources :tickets do
        get :assign, on: :member
      end
      resources :ticket_types
      resources :faqs do
        post :sort, on: :collection
      end
      resources :subscribers
      root :to => "tickets#index"
    end

    resources :faqs, :only => [ :index ]
    resources :tickets, :except => [ :edit, :destroy]
    root :to => "tickets#index"

    
  end
end

app/models/helpdesk/faq.rb
module Helpdesk
  class Faq < ActiveRecord::Base
    translates :title, :text
    accepts_nested_attributes_for :translations

    default_scope order('position ASC').includes(:translations)

    scope :active,  -> {where(active:  true)}
    scope :inactive,  -> {where(active: false)}
  end
end

app/controllers/helpdesk/admin/faqs_controller.rb
class Helpdesk::Admin::FaqsController < Helpdesk::Admin::BaseController

  def sort
    params[:faqs].each_with_index do |id, index|
      Helpdesk::Faq.update_all(['position=?', index+1], ['id=?', id])
    end
    render :nothing => true
  end
  # GET /faqs
  # GET /faqs.json
  def index
    if params[:faqs] == 'active'
      @faqs = Helpdesk::Faq.active
    elsif params[:faqs] == 'inactive'
      @faqs = Helpdesk::Faq.inactive
    else
      @faqs = Helpdesk::Faq.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faqs }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @faq = Helpdesk::Faq.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/new
  # GET /faqs/new.json
  def new
    @faq = Helpdesk::Faq.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/1/edit
  def edit
    @faq = Helpdesk::Faq.find(params[:id])
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Helpdesk::Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to admin_faqs_url, notice: 'Faq was successfully created.' }
        format.json { render json: @faq, status: :created, location: @faq }
      else
        format.html { render action: "new" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /faqs/1
  # PUT /faqs/1.json
  def update
    @faq = Helpdesk::Faq.find(params[:id])

    respond_to do |format|
      if @faq.update_attributes(faq_params)
        format.html { redirect_to admin_faqs_url, notice: 'Faq was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq = Helpdesk::Faq.find(params[:id])
    @faq.destroy

    respond_to do |format|
      format.html { redirect_to admin_faqs_url }
      format.json { head :no_content }
    end
  end

  private
  def faq_params
    params.require(:faq).permit(:active, :position, :title, :text, translations_attributes:[:id,:locale,:title,:text])
  end
end

app/controllers/helpdesk/faqs_controller.rb
module Helpdesk
  class FaqsController < Helpdesk::ApplicationController
    def index
      @faqs = Helpdesk::Faq.active
    end
  end
end

app/helpers/helpdesk/faqs_helper.rb
module Helpdesk
  module FaqsHelper
  end
end

app/views/helpdesk/admin/faqs/_form.html.haml
= simple_form_for [:admin,@faq],:html => {:novalidate => true} do |f|
  - if @faq.errors.any?
    #error_explanation
      %h2= "#{pluralize(@faq.errors.count, "error")} prohibited this faq from being saved:"
      %ul
        - @faq.errors.full_messages.each do |msg|
          %li= msg
  = f.input :active



  - I18n.available_locales.each do |locale|
    %h1
      = locale
      = f.globalize_fields_for locale do |g|
        = g.input :title
        = g.input :text, :as => :ckeditor, :input_html => { :ckeditor => {:width=>'100%',:height => 200,:toolbar => 'Full'} }


  = f.submit 'Save', :class=>'btn btn-primary'

app/views/helpdesk/admin/faqs/_menu.html.haml
- content_for :left do
  = menu_left t('helpdesk.faqs.title') do
    = menu_li ico('pencil') + t('helpdesk.faqs.new'), new_admin_faq_url
    %li.divider
    = menu_li ico('envelope') + "#{t('helpdesk.faqs.active')} (#{Helpdesk::Faq.active.count})", admin_faqs_url(:faqs => 'active')

    = menu_li ico('info-sign') + "#{t('helpdesk.faqs.inactive')} (#{Helpdesk::Faq.inactive.count})", admin_faqs_url(:faqs => 'inactive')
    %li.divider
    = menu_li ico('list') + t('helpdesk.faqs.all'), admin_faqs_url(:faqs => 'all')

app/views/helpdesk/admin/faqs/edit.html.haml
= render 'menu'


- content_for :title do
  Edycja pytania

= render 'form'

= link_to 'Show', [:admin,@faq]
\|
= link_to 'Back', admin_faqs_path

app/views/helpdesk/admin/faqs/index.html.haml
= render 'menu'

- content_for :title do
  -if params[:faqs] && params[:faqs] == 'active'
    = t('helpdesk.faqs.active')
  -elsif params[:faqs] && params[:faqs] == 'inactive'
    = t('helpdesk.faqs.inactive')
  -else
    = t('helpdesk.faqs.all')




%ul.unstyled#faqs
  - @faqs.each do |faq|
    %li.row{id:"faqs_#{faq.id}",style:'padding:5px 0px;'}
      %div.handle.span2{style:'cursor:move'}
        %span
          = ico('move')
        %span.badge.badge-info
          = "link#{faq.id}"
        - if faq.active
          %span.label.label-success
            = t('helpdesk.faqs.faq.active')
        - else
          %span.label
            = t('helpdesk.faqs.faq.inactive')
      %div.span5
        = faq.title
      %div.span2
        = link_to t('helpdesk.show'), admin_faq_path(faq), class: 'btn btn-info btn-mini'
        = link_to t('helpdesk.edit'), edit_admin_faq_path(faq),class: 'btn btn-primary btn-mini'
        = link_to t('helpdesk.destroy'), admin_faq_path(faq), method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-danger btn-mini'


- content_for :scripts do
  :javascript
    $(document).ready(function(){
      $('#faqs').sortable({
      axis: 'y',
      dropOnEmpty: false,
      handle: '.handle',
      cursor: 'crosshair',
      items: 'li',
      opacity: 0.4,
      scroll: true,
      update: function(){
      $.ajax({
      type: 'post',
      data: $('#faqs').sortable('serialize'),
      dataType: 'script',
      complete: function(request){
        $('#faqs').effect('highlight');
      },
      url: '#{sort_admin_faqs_path}'
        })
      }
      });
    });

app/views/helpdesk/admin/faqs/new.html.haml
= render 'menu'
- content_for :title do
  New faq

= render 'form'

= link_to 'Back', admin_faqs_path

app/views/helpdesk/admin/faqs/show.html.haml
= render 'menu'

%p#notice= notice

%p
  %b Aktywne:
  = @faq.active
%p
  %b Title:
  = @faq.title
%p
  %b Text:
  = raw @faq.text



= link_to 'Edit', edit_admin_faq_path(@faq)
\|
= link_to 'Back', admin_faqs_path