config/routes.rb
Helpdesk::Engine.routes.draw do
  default_url_options :host => "suporte.neemo.com.br"
# Rails.application.routes.draw do
  scope "(:locale)", :locale => /pl|pt|en/ do
    
    
    # Admin only roots
    namespace :admin do
      resources :tickets do
        get :assign, on: :member
      end
      resources :ticket_types
      resources :faqs do
        post :sort, on: :collection
      end
      resources :subscribers
      root :to => "tickets#index"
    end

    resources :faqs, :only => [ :index ]
    resources :tickets, :except => [ :edit, :destroy]
    root :to => "tickets#index"

    
  end
end

app/models/helpdesk/ticket.rb
module Helpdesk
  class Ticket < ActiveRecord::Base

    STATUSES = [
      [ :new,        'label-primary',3],
      [ :open,        'label-warning',2],
      [ :waiting,     'label-info',2],
      [ :solved,      'label-success',0],
      [ :not_fixable, 'label-default',-1],
      [ :unreachable, 'label-default',-1],
      [ :bug,         'label-default',-1]
    ]
    STATUS_BY_KEY = Hash[*STATUSES.map { |i| [i[0], i[1]] }.flatten]
    STATUS_CLASS_BY_KEY= Hash[*STATUSES.map { |i| [i[0], i[1]] }.flatten]
    STATUS_STATUS_BY_KEY= Hash[*STATUSES.map { |i| [i[0], i[2]] }.flatten]
    OPEN_STATUSES_KEYS =  STATUSES.map { |i| (i[2]>0 ? i[0] : nil)}.compact


    belongs_to :requester, :class_name => Helpdesk.user_class.to_s
    belongs_to :assignee, :class_name => Helpdesk.user_class.to_s
    belongs_to :ticket_type, :class_name => Helpdesk::TicketType
    has_many :comments, -> {order("created_at DESC")},:dependent => :destroy


    scope :active,   -> {where('status IN (?) ',OPEN_STATUSES_KEYS)}
    scope :unassigned,   -> {where('status IN (?) ',OPEN_STATUSES_KEYS).where('assignee_id is null')}
    scope :closed, -> { where('status NOT IN (?)',OPEN_STATUSES_KEYS)}
    default_scope -> { includes(:comments=>[:author])
    .includes(:requester)
    .includes(:assignee)
    .includes(:ticket_type)
    .order('id DESC')}

    validates_presence_of :description,:requester,:ticket_type_id

    accepts_nested_attributes_for :comments,:reject_if => lambda { |a| a[:comment].blank? }


    before_create :set_subject
    before_create :set_status
    after_create  :send_email

    def set_status
      if self.status.blank?
        self.status = :new
      end
    end

    def set_subject
      if self.created_at.nil?
        time = Time.now
      else
        time = self.created_at
      end

      new_subject = "#{sprintf '%02d',time.year-2000}#{sprintf '%02d',time.month}#{sprintf '%02d',time.day}"

      day_num = Helpdesk::Ticket.where(created_at: Date.today.beginning_of_day..Date.today.end_of_day).count+1
      new_subject += "-#{sprintf '%04d',day_num}: "
      self.subject = new_subject + subject.to_s
      self.subject.strip!
    end



    def send_email
      Helpdesk::NotificationsMailer.ticket_created_notification(self).deliver
      unless requester.email.empty?
        Helpdesk::NotificationsMailer.ticket_created_confirmation(self).deliver if Helpdesk.send_confirmation_emails
      end
    end

    def open?
      if self.status.blank? || STATUS_STATUS_BY_KEY[self.status.to_sym] > 0
        true
      else
        false
      end
    end




  end
end

app/models/helpdesk/ticket_type.rb
module Helpdesk
  class TicketType < ActiveRecord::Base
    translates :title
    accepts_nested_attributes_for :translations

    default_scope ->{order('position ASC')}

    scope :active,  -> {where(active:  true)}
    scope :inactive,  -> {where(active: false)}

  end
end

app/controllers/helpdesk/admin/tickets_controller.rb
class Helpdesk::Admin::TicketsController < Helpdesk::Admin::BaseController

  def index
    if params[:tickets] == 'unassigned'
      @tickets = Helpdesk::Ticket.unassigned.scoped
    elsif params[:tickets] == 'closed'
      @tickets = Helpdesk::Ticket.closed.scoped
    elsif params[:tickets] == 'active'
      @tickets = Helpdesk::Ticket.active.scoped
    elsif params[:tickets] == 'all'
      @tickets = Helpdesk::Ticket.scoped
    else
      @tickets = my_tickets.active
    end
    @tickets = @tickets.includes(:requester)
                        .includes(:assignee)
                        .includes(:ticket_type)
                        .page(params[:page])

    render 'list'
  end

  def assign
    @ticket = Helpdesk::Ticket.find(params[:id])
    if @ticket.update_column(:assignee_id, helpdesk_user)
      redirect_to admin_ticket_path,
        notice: t('helpdesk.tickets.is_now_assigned',subject: @ticket.subject)
    else
      redirect_to admin_ticket_path
    end
  end

  def new
    @ticket = Helpdesk::Ticket.new
    @ticket.status = Helpdesk::Ticket::STATUSES[0][0]
  end

  def edit
    @ticket = Helpdesk::Ticket.find(params[:id])

  end

  def show
    @ticket = Helpdesk::Ticket.find(params[:id])

  end

  def create
    @ticket = Helpdesk::Ticket.new(ticket_params)
    if @ticket.save
      redirect_to admin_ticket_path(@ticket)
    else
      render action: "new"
    end
  end

  def update
    @ticket = Helpdesk::Ticket.find(params[:id])
    if @ticket.update_attributes(ticket_params)
      unless @ticket.assignee
        @ticket.update_column(:assignee_id, helpdesk_user)
      end
      redirect_to admin_ticket_path
    else
      render action: "new"
    end
  end


   private

    def ticket_params
      params.require(:ticket).permit(:status,:requester_id,:assignee_id,:ticket_type_id, :subject, :description,comments_attributes:[:author_id, :comment, :public])
    end

end

app/controllers/helpdesk/tickets_controller.rb
module Helpdesk
  class TicketsController < Helpdesk::ApplicationController

    helper TicketsHelper

    # GET /tickets
    # GET /tickets.json
    def index
      if params[:tickets] == 'closed'
        @tickets = Helpdesk::Ticket.where(:requester_id => helpdesk_user.id).closed.page(params[:page])
      else
        @tickets = Helpdesk::Ticket.where(:requester_id => helpdesk_user.id).active.page(params[:page])
      end


      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @tickets }
      end
    end

    # GET /tickets/1
    # GET /tickets/1.json
    def show
      @tickets_count = Helpdesk::Ticket.where(:requester_id => helpdesk_user.id).active.count
      @ticket = Helpdesk::Ticket.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @ticket }
      end
    end

    # GET /tickets/new
    # GET /tickets/new.json
    def new
      @tickets_count = Helpdesk::Ticket.where(:requester_id => helpdesk_user.id).active.count
      @ticket = Helpdesk::Ticket.new
      @ticket.status = Helpdesk::Ticket::STATUSES[0][0]

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @ticket }
      end
    end

    def create
      @ticket = Helpdesk::Ticket.new(ticket_params)
      @ticket.requester = helpdesk_user
      @ticket.status = Helpdesk::Ticket::STATUSES[0][0]

      respond_to do |format|
        if @ticket.save
          format.html { redirect_to tickets_url, notice: 'Ticket was successfully created.' }
          format.json { render json: @ticket, status: :created, location: @ticket }
        else
          format.html { render action: "new" }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /tickets/1
    # PUT /tickets/1.json
    def update
      @ticket = Helpdesk::Ticket.find(params[:id])

      respond_to do |format|
        if @ticket.update_attributes(ticket_params)
          format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.'}
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end
    end


    private

    def ticket_params
      params.require(:ticket).permit( :ticket_type_id, :subject, :description,comments_attributes:[:author_id, :comment, :public])
    end

  end
end

app/helpers/helpdesk/admin/tickets_helper.rb
module Helpdesk
  module Admin::TicketsHelper
    def humanize_with_i18n(string, scope = [])
      I18n.t string, scope: scope, default: string.humanize
    end

    # The method prefix tells me that this should be in an object
    # But it doesn't belong in our model, does it?
    def tickets_statuses_for_select
      Helpdesk::Ticket::STATUSES.map { |s| [humanize_with_i18n(s[0].to_s,'helpdesk.tickets.statuses'),s[0]] }
    end
  end
end

app/helpers/helpdesk/tickets_helper.rb
module Helpdesk
  module TicketsHelper



  end
end

app/views/helpdesk/admin/tickets/_form.html.haml
= simple_form_for([:admin, @ticket]) do |f|
  - if @ticket.errors.any?
    %div.error_explanation
      %h2
        = "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
      %ul
        - @ticket.errors.full_messages.each do |msg|
          %li
            = msg
  = f.association :requester, :collection => (Helpdesk.user_class).all,:label_method=>Helpdesk.display_user_uniq_info.to_sym, input_html: { class: 'chosen-select' }
  = f.input :subject
  = f.input :status, :collection => tickets_statuses_for_select, include_blank: false
  = f.input :assignee, :collection => helpdesk_admin_collection
  = f.input :ticket_type_id, :collection => Helpdesk::TicketType.active,include_blank: false
  - if @ticket.new_record?
    = f.input :description,input_html:{rows:4}
  - else
    = simple_format @ticket.description


  %div.form-actions
    = f.button :submit, :class => 'btn btn-primary'
    = submit_tag t('helpdesk..tickets.cancel'), :type => :reset, :class => "btn btn-danger"

app/views/helpdesk/admin/tickets/_menu.html.haml
- content_for :left do
  = menu_left t('helpdesk.tickets.title') do
    = menu_li ico('pencil') + t('helpdesk.ticket.new'), new_admin_ticket_url
    %li.divider
    = menu_li ico('eye-open') + "#{t('helpdesk.tickets.my')} (#{@my_tickets.size})", admin_tickets_url 
    = menu_li ico('bullhorn') + "#{t('helpdesk.tickets.active')} ", admin_tickets_url(:tickets => 'active')
    /(#{Helpdesk::Ticket.active.count})

    %li.divider
    = menu_li ico('folder-open') + "#{t('helpdesk.tickets.unassigned')} (#{Helpdesk::Ticket.unassigned.count})", admin_tickets_url(:tickets => 'unassigned')
    = menu_li ico('hdd') + "#{t('helpdesk.tickets.closed')} ", admin_tickets_url(:tickets => 'closed')
    / (#{Helpdesk::Ticket.closed.count})
    = menu_li ico('list-alt') + t('helpdesk.tickets.all'), admin_tickets_url(:tickets => 'all')

    %li.divider
    %li.divider
      = menu_li ico('edit') + t('helpdesk.ticket_types.title'), admin_ticket_types_url    

app/views/helpdesk/admin/tickets/_ticket.html.haml
%table.table.table-bordered
  %tbody
    %tr{:class=>ticket.ticket_type.tr_class}
      %td{colspan:2}
        %h4
          ="##{ticket.subject}"
    %tr
      %td{style:'width:100px'}
        = I18n::l(ticket.created_at, :format=>:short)
        - if ticket.requester
          = ticket.requester.send Helpdesk.display_user_uniq_info.to_sym
      %td{rowspan:2}
        = status_label humanize_with_i18n(ticket.status,'helpdesk.tickets.statuses'), Helpdesk::Ticket::STATUS_CLASS_BY_KEY[ticket.status.to_sym]

        = ticket.ticket_type.title
        = auto_link(simple_format(ticket.description), :html => { :target => "_blank" })
    %tr
      %td
        - if ticket.assignee
          = t('helpdesk.tickets.assignee_to')
          = ticket.assignee.send Helpdesk.display_user_uniq_info.to_sym
        - else
          = t('helpdesk.tickets.not_assigned')
          = link_to ico('star') + t('helpdesk.tickets.assign_me'), assign_admin_ticket_path(ticket),class: 'btn btn-mini btn-info'
    %tr
      %td
        %span.btn.disabled
          = ico('comment')
          = ticket.comments.size
      %td
        %ul.comments.unstyled
          - ticket.comments.each do |comment|
            - if comment.persisted?
              %li.comment{:id=>"comment#{comment.id}"}
                %div.comment-left
                  - if comment.public
                    = status_label ico('envelope') + t('helpdesk.comments.send') ,'label-success'
                  - else
                    = status_label t('helpdesk.comments.note'),''
                  %br
                  %a{class:'anchor', href: "#comment#{comment.id}"}
                    = "#"
                %div.comment-header
                  -if comment.author == ticket.requester
                    = status_label ico('user')+ t('helpdesk.comments.author'),'label-info'
                  = comment.author.send Helpdesk.display_user_uniq_info.to_sym if comment.author
                  %small
                    = time_ago_in_words(comment.created_at)
                    temu
                %div.comment-body
                  = auto_link(simple_format(comment.comment), :html => { :target => "_blank" })

    %tr{:class=>ticket.ticket_type.tr_class}
      %td{colspan:2}
        - if show_button
          = link_to 'Show', admin_ticket_url(ticket), class: 'btn btn-block'
        -elsif edit_button
          = link_to 'Edit', edit_admin_ticket_url(ticket), class: 'btn btn-primary'

app/views/helpdesk/admin/tickets/edit.html.haml
= render 'menu'
- content_for :title do
  = t('helpdesk.ticket')
  = "##{@ticket.subject}"
= render 'form'
%h2
  = t('helpdesk.comments.title')

%ul.comments.unstyled
  - @ticket.comments.each do |comment|
    - if comment.persisted?
      %li.comment{:id=>"comment#{comment.id}"}
        %div.comment-left
          - if comment.public
            = status_label ico('envelope') + t('helpdesk.comments.send') ,'label-success'
          - else
            = status_label t('helpdesk.comments.note'),''
          %br
          %a{class:'anchor', href: "#comment#{comment.id}"}
            = "#"
        %div.comment-header
          -if comment.author == @ticket.requester
            = status_label ico('user')+ t('helpdesk.comments.author'),'label-info'

          = comment.author.send Helpdesk.display_user.to_sym if comment.author
          %small
            = time_ago_in_words(comment.created_at)
            temu
        %div.comment-body
          = simple_format comment.comment

app/views/helpdesk/admin/tickets/index.html.haml
= render 'menu'

%h1
  -if params[:tickets] && params[:tickets] == 'unassigned'
    = t('helpdesk.unassigned_ticketes')
  -else
    = t('helpdesk.my_tickets')

%table.table.table-hover
  %thead
    %tr
      %th= t('helpdesk.status')
      %th ID
      %th Issue Type
      %th Subject
      %th Requester
      %th Requested
      %th Assignee
      %th

  %tbody
    - @tickets.each do |ticket|
      %tr{:class=>ticket.ticket_type.tr_class}
        %td
          = Helpdesk::Ticket::STATUS_BY_KEY[ticket.status.to_sym]
        %td= ticket.id
        %td= ticket.ticket_type.title
        %td= ticket.subject
        %td
          - if ticket.requester
            = ticket.requester.send Helpdesk.display_user.to_sym
            %br
            = ticket.requester.phone
            %br
            = ticket.requester.email
        %td= I18n::l(ticket.created_at, :format=>:short)
        %td= ticket.assignee if ticket.assignee
        %td= link_to 'Show', admin_ticket_url(ticket)
%br

= paginate @tickets

app/views/helpdesk/admin/tickets/list.html.haml
= render 'menu'

- content_for :title do
  -if params[:tickets] && params[:tickets] == 'unassigned'
    = t('helpdesk.tickets.unassigned')
  -elsif params[:tickets] && params[:tickets] == 'closed'
    = t('helpdesk.tickets.closed')
  -elsif params[:tickets] && params[:tickets] == 'active'
    = t('helpdesk.tickets.active')
  -elsif params[:tickets] && params[:tickets] == 'all'
    = t('helpdesk.tickets.all')
  -else
    = t('helpdesk.tickets.my')

- @tickets.each do |ticket|
  = render 'ticket', ticket: ticket, show_button:true

= paginate @tickets

app/views/helpdesk/admin/tickets/new.html.haml
= render 'menu'
- content_for :title do
  = t('helpdesk.new_ticket')
= render 'form'

app/views/helpdesk/admin/tickets/show.html.haml
= render 'menu'

= render 'ticket', :ticket=>@ticket, show_button:false,edit_button:true

%table.table
  %tbody
    %tr{:class=>@ticket.ticket_type.tr_class}

      %td

        - unless @ticket.open?
          = t('helpdesk.tickets.ticket_closed')
        -else
          = simple_form_for([:admin, @ticket]) do |f|
            - if @ticket.errors.any?
              %div.error_explanation
                %h2
                  = "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
                %ul
                  - @ticket.errors.full_messages.each do |msg|
                    %li
                      = msg
            = f.input :status, :collection => tickets_statuses_for_select, include_blank: false
            = f.input :assignee_id, :collection => helpdesk_admin_collection


            = f.simple_fields_for :comments,@ticket.comments.build do |tickets_form|
              - unless tickets_form.object.persisted?
                = tickets_form.input :comment, :input_html=>{class: 'comment-textarea'}
                / , :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'mini'},:language => I18n.locale}

                = tickets_form.input :public, :hint => t('helpdesk.tickets.visible_to_autor')
                = tickets_form.input :author_id, :as => :hidden, :input_html => { :value => helpdesk_user.id }
            %div.form-actions
              = f.button :submit, :class => 'btn btn-primary'
              = submit_tag t('helpdesk..tickets.cancel'), :type => :reset, :class => "btn btn-danger"